# The time in seconds between each regen tick
period: 2.0
# The amount of health gained each regen tick
amount: 1.0
# Whether the food will impact the regen rate
use-food-level: true
# How much time in seconds a player remains in combat
combat-duration: 5.0